#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wcast-qual"
#define __NV_CUBIN_HANDLE_STORAGE__ static
#include "crt/host_runtime.h"
#include "test_norm.fatbin.c"
static void __device_stub__Z16kernel_DZdreduceILj1024EEvPdP7double2S0_i(double *, cuDoubleComplex *, double *, int);
static void __device_stub__Z16kernel_DZdreduceILj512EEvPdP7double2S0_i(double *, cuDoubleComplex *, double *, int);
static void __device_stub__Z16kernel_DZdreduceILj256EEvPdP7double2S0_i(double *, cuDoubleComplex *, double *, int);
static void __device_stub__Z16kernel_DZdreduceILj128EEvPdP7double2S0_i(double *, cuDoubleComplex *, double *, int);
static void __device_stub__Z16kernel_DZdreduceILj64EEvPdP7double2S0_i(double *, cuDoubleComplex *, double *, int);
static void __nv_cudaEntityRegisterCallback(void **);
static void __sti____cudaRegisterAll_17_test_norm_cpp1_ii_d366c12b(void) __attribute__((__constructor__));
static void __device_stub__Z16kernel_DZdreduceILj1024EEvPdP7double2S0_i(double *__par0, cuDoubleComplex *__par1, double *__par2, int __par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)1024u> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_DZdreduce<1024U>( double *&__cuda_0,::cuDoubleComplex *&__cuda_1,double *&__cuda_2,int &__cuda_3){__device_stub__Z16kernel_DZdreduceILj1024EEvPdP7double2S0_i( (double *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1,(double *&)__cuda_2,(int &)__cuda_3);}
static void __device_stub__Z16kernel_DZdreduceILj512EEvPdP7double2S0_i(double *__par0, cuDoubleComplex *__par1, double *__par2, int __par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)512u> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_DZdreduce<512U>( double *&__cuda_0,::cuDoubleComplex *&__cuda_1,double *&__cuda_2,int &__cuda_3){__device_stub__Z16kernel_DZdreduceILj512EEvPdP7double2S0_i( (double *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1,(double *&)__cuda_2,(int &)__cuda_3);}
static void __device_stub__Z16kernel_DZdreduceILj256EEvPdP7double2S0_i(double *__par0, cuDoubleComplex *__par1, double *__par2, int __par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)256u> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_DZdreduce<256U>( double *&__cuda_0,::cuDoubleComplex *&__cuda_1,double *&__cuda_2,int &__cuda_3){__device_stub__Z16kernel_DZdreduceILj256EEvPdP7double2S0_i( (double *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1,(double *&)__cuda_2,(int &)__cuda_3);}
static void __device_stub__Z16kernel_DZdreduceILj128EEvPdP7double2S0_i(double *__par0, cuDoubleComplex *__par1, double *__par2, int __par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)128u> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_DZdreduce<128U>( double *&__cuda_0,::cuDoubleComplex *&__cuda_1,double *&__cuda_2,int &__cuda_3){__device_stub__Z16kernel_DZdreduceILj128EEvPdP7double2S0_i( (double *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1,(double *&)__cuda_2,(int &)__cuda_3);}
static void __device_stub__Z16kernel_DZdreduceILj64EEvPdP7double2S0_i(double *__par0, cuDoubleComplex *__par1, double *__par2, int __par3){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaSetupArgSimple(__par2, 16UL);__cudaSetupArgSimple(__par3, 24UL);__cudaLaunch(((char *)((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)64u> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_DZdreduce<64U>( double *&__cuda_0,::cuDoubleComplex *&__cuda_1,double *&__cuda_2,int &__cuda_3){__device_stub__Z16kernel_DZdreduceILj64EEvPdP7double2S0_i( (double *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1,(double *&)__cuda_2,(int &)__cuda_3);}
static void __nv_cudaEntityRegisterCallback(void **__T21){__nv_dummy_param_ref(__T21);__nv_save_fatbinhandle_for_managed_rt(__T21);__cudaRegisterEntry(__T21, ((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)64u> ), _Z16kernel_DZdreduceILj64EEvPdP7double2S0_i, (-1));__cudaRegisterEntry(__T21, ((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)128u> ), _Z16kernel_DZdreduceILj128EEvPdP7double2S0_i, (-1));__cudaRegisterEntry(__T21, ((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)256u> ), _Z16kernel_DZdreduceILj256EEvPdP7double2S0_i, (-1));__cudaRegisterEntry(__T21, ((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)512u> ), _Z16kernel_DZdreduceILj512EEvPdP7double2S0_i, (-1));__cudaRegisterEntry(__T21, ((void ( *)(double *, cuDoubleComplex *, double *, int))kernel_DZdreduce<(unsigned int)1024u> ), _Z16kernel_DZdreduceILj1024EEvPdP7double2S0_i, (-1));__cudaRegisterVariable(__T21, __shadow_var(retirementCount,::retirementCount), 0, 4, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust6system6detail10sequential3seqE,::thrust::system::detail::sequential::seq), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust6system4cuda6detail5bulk_4rootE,::thrust::system::cuda::detail::bulk_::root), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_1E,::thrust::placeholders::_1), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_2E,::thrust::placeholders::_2), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_3E,::thrust::placeholders::_3), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_4E,::thrust::placeholders::_4), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_5E,::thrust::placeholders::_5), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_6E,::thrust::placeholders::_6), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_7E,::thrust::placeholders::_7), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_8E,::thrust::placeholders::_8), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders2_9E,::thrust::placeholders::_9), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust12placeholders3_10E,::thrust::placeholders::_10), 0, 1, 0, 0);__cudaRegisterVariable(__T21, __shadow_var(_ZN6thrust3seqE,::thrust::seq), 0, 1, 0, 0);}
static void __sti____cudaRegisterAll_17_test_norm_cpp1_ii_d366c12b(void){__cudaRegisterBinary(__nv_cudaEntityRegisterCallback);}

#pragma GCC diagnostic pop
