#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wcast-qual"
#define __NV_CUBIN_HANDLE_STORAGE__ static
#include "crt/host_runtime.h"
#include "Coulomb.fatbin.c"
static void __device_stub__Z29__kernel_enlarge_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvP7double2Pd(cuDoubleComplex *, double *);
static void __device_stub__Z26kernel_coulomb_sph_cutoff0ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *, cuDoubleComplex *);
static void __device_stub__Z26kernel_coulomb_sph_cutoff1ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *, cuDoubleComplex *);
static void __device_stub__Z26kernel_coulomb_sph_cutoff2ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *, cuDoubleComplex *);
static void __device_stub__Z31kernel_coulomb_sph_cutoff_cnst0ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *, cuDoubleComplex *);
static void __device_stub__Z31kernel_coulomb_sph_cutoff_cnst1ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *, cuDoubleComplex *);
static void __device_stub__Z31kernel_coulomb_sph_cutoff_cnst2ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *, cuDoubleComplex *);
static void __device_stub__Z28__kernel_lessen_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvPdS0_(double *, double *);
static void __nv_cudaEntityRegisterCallback(void **);
static void __sti____cudaRegisterAll_15_Coulomb_cpp1_ii_9a02c5bc(void) __attribute__((__constructor__));
static void __device_stub__Z29__kernel_enlarge_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvP7double2Pd(cuDoubleComplex *__par0, double *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, double *))__kernel_enlarge_1Dindexing__<(unsigned int)64u, (unsigned int)48u, (unsigned int)32u, (unsigned int)64u, (unsigned int)72u, (unsigned int)80u> )));}
template<> __specialization_static void __wrapper__device_stub___kernel_enlarge_1Dindexing__<64U,48U,32U,64U,72U,80U>( ::cuDoubleComplex *&__cuda_0,double *&__cuda_1){__device_stub__Z29__kernel_enlarge_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvP7double2Pd( (::cuDoubleComplex *&)__cuda_0,(double *&)__cuda_1);}
static void __device_stub__Z26kernel_coulomb_sph_cutoff0ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *__par0, cuDoubleComplex *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff0<(int)192, (int)192, (int)192> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_coulomb_sph_cutoff0<192,192,192>( ::cuDoubleComplex *&__cuda_0,::cuDoubleComplex *&__cuda_1){__device_stub__Z26kernel_coulomb_sph_cutoff0ILi192ELi192ELi192EEvP7double2S1_( (::cuDoubleComplex *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1);}
static void __device_stub__Z26kernel_coulomb_sph_cutoff1ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *__par0, cuDoubleComplex *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff1<(int)192, (int)192, (int)192> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_coulomb_sph_cutoff1<192,192,192>( ::cuDoubleComplex *&__cuda_0,::cuDoubleComplex *&__cuda_1){__device_stub__Z26kernel_coulomb_sph_cutoff1ILi192ELi192ELi192EEvP7double2S1_( (::cuDoubleComplex *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1);}
static void __device_stub__Z26kernel_coulomb_sph_cutoff2ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *__par0, cuDoubleComplex *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff2<(int)192, (int)192, (int)192> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_coulomb_sph_cutoff2<192,192,192>( ::cuDoubleComplex *&__cuda_0,::cuDoubleComplex *&__cuda_1){__device_stub__Z26kernel_coulomb_sph_cutoff2ILi192ELi192ELi192EEvP7double2S1_( (::cuDoubleComplex *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1);}
static void __device_stub__Z31kernel_coulomb_sph_cutoff_cnst0ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *__par0, cuDoubleComplex *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff_cnst0<(int)192, (int)192, (int)192> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_coulomb_sph_cutoff_cnst0<192,192,192>( ::cuDoubleComplex *&__cuda_0,::cuDoubleComplex *&__cuda_1){__device_stub__Z31kernel_coulomb_sph_cutoff_cnst0ILi192ELi192ELi192EEvP7double2S1_( (::cuDoubleComplex *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1);}
static void __device_stub__Z31kernel_coulomb_sph_cutoff_cnst1ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *__par0, cuDoubleComplex *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff_cnst1<(int)192, (int)192, (int)192> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_coulomb_sph_cutoff_cnst1<192,192,192>( ::cuDoubleComplex *&__cuda_0,::cuDoubleComplex *&__cuda_1){__device_stub__Z31kernel_coulomb_sph_cutoff_cnst1ILi192ELi192ELi192EEvP7double2S1_( (::cuDoubleComplex *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1);}
static void __device_stub__Z31kernel_coulomb_sph_cutoff_cnst2ILi192ELi192ELi192EEvP7double2S1_(cuDoubleComplex *__par0, cuDoubleComplex *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff_cnst2<(int)192, (int)192, (int)192> )));}
template<> __specialization_static void __wrapper__device_stub_kernel_coulomb_sph_cutoff_cnst2<192,192,192>( ::cuDoubleComplex *&__cuda_0,::cuDoubleComplex *&__cuda_1){__device_stub__Z31kernel_coulomb_sph_cutoff_cnst2ILi192ELi192ELi192EEvP7double2S1_( (::cuDoubleComplex *&)__cuda_0,(::cuDoubleComplex *&)__cuda_1);}
static void __device_stub__Z28__kernel_lessen_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvPdS0_(double *__par0, double *__par1){__cudaSetupArgSimple(__par0, 0UL);__cudaSetupArgSimple(__par1, 8UL);__cudaLaunch(((char *)((void ( *)(double *, double *))__kernel_lessen_1Dindexing__<(unsigned int)64u, (unsigned int)48u, (unsigned int)32u, (unsigned int)64u, (unsigned int)72u, (unsigned int)80u> )));}
template<> __specialization_static void __wrapper__device_stub___kernel_lessen_1Dindexing__<64U,48U,32U,64U,72U,80U>( double *&__cuda_0,double *&__cuda_1){__device_stub__Z28__kernel_lessen_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvPdS0_( (double *&)__cuda_0,(double *&)__cuda_1);}
static void __nv_cudaEntityRegisterCallback(void **__T236){__nv_dummy_param_ref(__T236);__nv_save_fatbinhandle_for_managed_rt(__T236);__cudaRegisterEntry(__T236, ((void ( *)(double *, double *))__kernel_lessen_1Dindexing__<(unsigned int)64u, (unsigned int)48u, (unsigned int)32u, (unsigned int)64u, (unsigned int)72u, (unsigned int)80u> ), _Z28__kernel_lessen_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvPdS0_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff_cnst2<(int)192, (int)192, (int)192> ), _Z31kernel_coulomb_sph_cutoff_cnst2ILi192ELi192ELi192EEvP7double2S1_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff_cnst1<(int)192, (int)192, (int)192> ), _Z31kernel_coulomb_sph_cutoff_cnst1ILi192ELi192ELi192EEvP7double2S1_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff_cnst0<(int)192, (int)192, (int)192> ), _Z31kernel_coulomb_sph_cutoff_cnst0ILi192ELi192ELi192EEvP7double2S1_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff2<(int)192, (int)192, (int)192> ), _Z26kernel_coulomb_sph_cutoff2ILi192ELi192ELi192EEvP7double2S1_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff1<(int)192, (int)192, (int)192> ), _Z26kernel_coulomb_sph_cutoff1ILi192ELi192ELi192EEvP7double2S1_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, cuDoubleComplex *))kernel_coulomb_sph_cutoff0<(int)192, (int)192, (int)192> ), _Z26kernel_coulomb_sph_cutoff0ILi192ELi192ELi192EEvP7double2S1_, (-1));__cudaRegisterEntry(__T236, ((void ( *)(cuDoubleComplex *, double *))__kernel_enlarge_1Dindexing__<(unsigned int)64u, (unsigned int)48u, (unsigned int)32u, (unsigned int)64u, (unsigned int)72u, (unsigned int)80u> ), _Z29__kernel_enlarge_1Dindexing__ILj64ELj48ELj32ELj64ELj72ELj80EEvP7double2Pd, (-1));__cudaRegisterVariable(__T236, __shadow_var(d_charge,::d_charge), 0, 8, 1, 0);__cudaRegisterVariable(__T236, __shadow_var(d_lcutoff,::d_lcutoff), 0, 8, 1, 0);__cudaRegisterVariable(__T236, __shadow_var(d_kkx,::d_kkx), 0, 1536, 1, 0);__cudaRegisterVariable(__T236, __shadow_var(d_kky,::d_kky), 0, 1536, 1, 0);__cudaRegisterVariable(__T236, __shadow_var(d_kkz,::d_kkz), 0, 1536, 1, 0);}
static void __sti____cudaRegisterAll_15_Coulomb_cpp1_ii_9a02c5bc(void){__cudaRegisterBinary(__nv_cudaEntityRegisterCallback);}

#pragma GCC diagnostic pop
